
---
deployment:
  tasks:
    - export REPOSITORY="/home4/eduar109/repositories/git_app_ligaglobal_cl/app.ligaglobal.cl/"
    - export DEPLOYPATH="/home4/eduar109/app.ligaglobal.cl/"
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/app $DEPLOYPATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/routes $DEPLOYPATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/resources $DEPLOYPATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/public $DEPLOYPATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/bootstrap $DEPLOYPATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/config $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm run build