
---
deployment:
  tasks:
    - export REPOSITORY="/home4/eduar109/repositories/git_app_ligaglobal_cl/app.ligaglobal.cl/"
    - export DEPLOYPATH="/home4/eduar109/app.ligaglobal.cl/"
    - cd $REPOSITORY
    - /bin/rsync -a --exclude 'index.php' --exclude '.env' --exclude '.env.example' --exclude '.htaccess' --exclude 'node_modules/' . $DEPLOYPATH
    