
---
deployment:
  tasks:
    - export REPOSITORY="/home4/eduar109/repositories/git_app_ligaglobal_cl/app.ligaglobal.cl/"
    - export DEPLOY_CONFIG="/home4/eduar109/repositories/git_app_ligaglobal_cl/documentos"
    - export DEPLOY_PATH="/home4/eduar109/app.ligaglobal.cl/"
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/app $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/routes $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/resources $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/public $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/bootstrap $DEPLOY_PATH
    - rsync -av --exclude='.git' --exclude='.htaccess' $REPOSITORY/config $DEPLOY_PATH
